{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "cdaf9581-a358-4e65-92d1-c55ed5ba7fb5",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'db'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[7], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mstreamlit\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mst\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdb\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mllm_engine\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m classify_query\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mrag_engine\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m query_kb\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'db'"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "from db import *\n",
    "from llm_engine import classify_query\n",
    "from rag_engine import query_kb\n",
    "from identity_matcher import resolve_identity\n",
    "\n",
    "st.set_page_config(page_title=\"BookLeaf Support Bot\")\n",
    "st.title(\"📚 BookLeaf Author Support\")\n",
    "\n",
    "# Initialize DB\n",
    "init_db()\n",
    "seed_data()\n",
    "\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state.messages = []\n",
    "\n",
    "user_email = st.text_input(\"Enter your registered email\")\n",
    "query = st.chat_input(\"Ask your query...\")\n",
    "\n",
    "if query and user_email:\n",
    "\n",
    "    escalated = False\n",
    "    error_message = None\n",
    "\n",
    "    try:\n",
    "        intent_data = classify_query(query)\n",
    "        intent = intent_data[\"intent\"]\n",
    "        confidence = intent_data[\"confidence\"]\n",
    "\n",
    "    except Exception:\n",
    "        intent = \"unknown\"\n",
    "        confidence = 0\n",
    "        escalated = True\n",
    "        response = \"🚨 AI system error. Human agent notified.\"\n",
    "\n",
    "    if not escalated and confidence < 80:\n",
    "        response = \"⚠️ Low confidence detected. Human agent will assist.\"\n",
    "        escalated = True\n",
    "\n",
    "    elif not escalated:\n",
    "        try:\n",
    "            author, id_conf = resolve_identity(user_email)\n",
    "\n",
    "            if not author:\n",
    "                response = \"❌ No author found.\"\n",
    "                escalated = True\n",
    "\n",
    "            elif id_conf < 70:\n",
    "                response = \"⚠️ Multiple profiles found. Manual verification required.\"\n",
    "                escalated = True\n",
    "\n",
    "            elif intent_data[\"requires_db\"]:\n",
    "                books = get_book_by_author(author[0])\n",
    "\n",
    "                if not books:\n",
    "                    response = \"No book found.\"\n",
    "                    escalated = True\n",
    "\n",
    "                elif len(books) > 1:\n",
    "                    response = \"Multiple books found. Please specify.\"\n",
    "                    escalated = True\n",
    "\n",
    "                else:\n",
    "                    book = books[0]\n",
    "\n",
    "                    if intent == \"book_live_status\":\n",
    "                        response = f\"🎉 Book Live Date: {book[4]}\"\n",
    "\n",
    "                    elif intent == \"royalty_status\":\n",
    "                        response = f\"💰 Royalty Status: {book[5]}\"\n",
    "\n",
    "                    elif intent == \"add_on_status\":\n",
    "                        response = f\"📦 Add-ons: {book[7]}\"\n",
    "\n",
    "                    else:\n",
    "                        response = \"Query requires support review.\"\n",
    "                        escalated = True\n",
    "            else:\n",
    "                response = f\"📘 {query_kb(query)}\"\n",
    "\n",
    "        except Exception as e:\n",
    "            response = \"🚨 System error. Human agent notified.\"\n",
    "            escalated = True\n",
    "            error_message = str(e)\n",
    "\n",
    "    log_query(\n",
    "        user_email,\n",
    "        query,\n",
    "        intent,\n",
    "        confidence,\n",
    "        response,\n",
    "        int(escalated),\n",
    "        error_message\n",
    "    )\n",
    "\n",
    "    st.chat_message(\"user\").write(query)\n",
    "    st.chat_message(\"assistant\").write(response)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b1ce75b5-3ef3-4fef-99ed-987a6a9279ef",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
