{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdaf9581-a358-4e65-92d1-c55ed5ba7fb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "from datetime import datetime\n",
    "\n",
    "DB_PATH = \"data/bookleaf.db\"\n",
    "\n",
    "\n",
    "def init_db():\n",
    "    conn = sqlite3.connect(DB_PATH)\n",
    "    c = conn.cursor()\n",
    "\n",
    "    c.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS authors (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        name TEXT,\n",
    "        email TEXT,\n",
    "        phone TEXT,\n",
    "        instagram TEXT\n",
    "    )\n",
    "    \"\"\")\n",
    "\n",
    "    c.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS books (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        author_id INTEGER,\n",
    "        book_title TEXT,\n",
    "        final_submission_date TEXT,\n",
    "        book_live_date TEXT,\n",
    "        royalty_status TEXT,\n",
    "        isbn TEXT,\n",
    "        add_on_services TEXT\n",
    "    )\n",
    "    \"\"\")\n",
    "\n",
    "    c.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS query_logs (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        user_identifier TEXT,\n",
    "        query TEXT,\n",
    "        intent TEXT,\n",
    "        confidence REAL,\n",
    "        response TEXT,\n",
    "        escalated INTEGER,\n",
    "        error TEXT,\n",
    "        timestamp TEXT\n",
    "    )\n",
    "    \"\"\")\n",
    "\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "\n",
    "def seed_data():\n",
    "    conn = sqlite3.connect(DB_PATH)\n",
    "    c = conn.cursor()\n",
    "\n",
    "    c.execute(\"DELETE FROM authors\")\n",
    "    c.execute(\"DELETE FROM books\")\n",
    "\n",
    "    c.execute(\"\"\"\n",
    "    INSERT INTO authors (name,email,phone,instagram)\n",
    "    VALUES ('Sara Johnson','sara.johnson@xyz.com','9876543210','@sarapoetry23')\n",
    "    \"\"\")\n",
    "\n",
    "    c.execute(\"\"\"\n",
    "    INSERT INTO books (\n",
    "        author_id,book_title,final_submission_date,\n",
    "        book_live_date,royalty_status,isbn,add_on_services\n",
    "    )\n",
    "    VALUES (\n",
    "        1,'Wings of Silence','2025-10-01',\n",
    "        '2026-01-12','Processing','978-93-111111','Bestseller Package'\n",
    "    )\n",
    "    \"\"\")\n",
    "\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "\n",
    "def get_author_by_email(email):\n",
    "    conn = sqlite3.connect(DB_PATH)\n",
    "    c = conn.cursor()\n",
    "    c.execute(\"SELECT * FROM authors WHERE email=?\", (email,))\n",
    "    results = c.fetchall()\n",
    "    conn.close()\n",
    "    return results\n",
    "\n",
    "\n",
    "def get_book_by_author(author_id):\n",
    "    conn = sqlite3.connect(DB_PATH)\n",
    "    c = conn.cursor()\n",
    "    c.execute(\"SELECT * FROM books WHERE author_id=?\", (author_id,))\n",
    "    results = c.fetchall()\n",
    "    conn.close()\n",
    "    return results\n",
    "\n",
    "\n",
    "def log_query(user, query, intent, conf, response, escalated, error=None):\n",
    "    conn = sqlite3.connect(DB_PATH)\n",
    "    c = conn.cursor()\n",
    "    c.execute(\"\"\"\n",
    "    INSERT INTO query_logs\n",
    "    (user_identifier,query,intent,confidence,response,escalated,error,timestamp)\n",
    "    VALUES (?,?,?,?,?,?,?,?)\n",
    "    \"\"\", (user, query, intent, conf, response, escalated,\n",
    "          error, datetime.now().isoformat()))\n",
    "    conn.commit()\n",
    "    conn.close()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
